<?php
/**
 * Ajindra : Create a simple HelloWorld frontend page, involving layout, block 
 * and template file as well
 *
 * @category   Ajindra_FrontendHelloWorldPage
 * @package    Ajindra_FrontendHelloWorldPage
 * @copyright  2020 All rights reserved.
 * @license    Proprietary
 * @author     Ajindra
 */

/**
 * @var \Ajindra\FrontendHelloWorldPage\Block\Index\SampleFrontendPage $block
 */
echo $block->sayHello();